title: Nat Drabik | Front-End Developer
description: Front-End Developer com background em Design Gráfico, localizada em Curitiba, Paraná.
baseurl: "https://natdrabik.github.io/"
url: "https://natdrabik.github.io/"